name: Meeting Notes Template
description: Template for recording meeting notes
title: "Meeting Notes - {{date}}"
labels: ["meeting-notes"]
body:
  - type: input
    id: meeting_title
    attributes:
      label: Meeting Title
      placeholder: e.g. Weekly Sync

  - type: input
    id: date
    attributes:
      label: Date
      placeholder: YYYY-MM-DD

  - type: input
    id: time
    attributes:
      label: Time
      placeholder: e.g. 10:00 AM - 11:00 AM

  - type: input
    id: location
    attributes:
      label: Location/Platform
      placeholder: e.g. Zoom / Room 205

  - type: textarea
    id: attendees
    attributes:
      label: Attendees
      placeholder: List of people attending

  - type: textarea
    id: agenda
    attributes:
      label: Agenda
      placeholder: Bullet points of agenda items

  - type: textarea
    id: discussion
    attributes:
      label: Discussion Notes
      placeholder: Notes and actions from the discussion

  - type: textarea
    id: decisions
    attributes:
      label: Decisions Made
      placeholder: Bullet points of decisions

  - type: textarea
    id: next_steps
    attributes:
      label: Next Steps
      placeholder: Bullet points with assigned members

  - type: input
    id: next_meeting_date
    attributes:
      label: Next Meeting Date
      placeholder: YYYY-MM-DD

  - type: input
    id: next_meeting_time
    attributes:
      label: Next Meeting Time
      placeholder: e.g. 11:00 AM
