type: custom
title: "Meeting Notes - [Enter Date]"

body:
  - type: input
    attributes:
      label: Meeting Title
      placeholder: e.g. Weekly Sync

  - type: input
    attributes:
      label: Date
      placeholder: YYYY-MM-DD

  - type: input
    attributes:
      label: Time
      placeholder: e.g. 10:00 AM - 11:00 AM

  - type: input
    attributes:
      label: Location / Platform
      placeholder: e.g. Zoom, MS Teams, Room 101

  - type: textarea
    attributes:
      label: Attendees
      placeholder: e.g. John, Sarah, Ahmed, Fatima

  - type: textarea
    attributes:
      label: Agenda
      placeholder: • Topic 1\n• Topic 2\n• Topic 3

  - type: textarea
    attributes:
      label: Discussion
      placeholder: Notes on each agenda topic and any key talking points

  - type: textarea
    attributes:
      label: Decisions Made
      placeholder: • Decision 1\n• Decision 2

  - type: textarea
    attributes:
      label: Action Items / Next Steps
      placeholder: • Task 1 (Assigned to Ahmed)\n• Task 2 (Assigned to Sarah)

  - type: input
    attributes:
      label: Next Meeting Date
      placeholder: YYYY-MM-DD

  - type: input
    attributes:
      label: Next Meeting Time
      placeholder: e.g. 11:00 AM
