CREATE TABLE ADMINS_ROLES (
    adminRoleId UUID PRIMARY KEY,
    adminId UUID NOT NULL REFERENCES ADMINS(adminId) ON DELETE CASCADE ON UPDATE CASCADE,
    roleId UUID NOT NULL REFERENCES ROLES(roleId) ON DELETE CASCADE ON UPDATE CASCADE
);