CREATE TABLE ANSWER_OPTIONS (
    answerOptionsId UUID PRIMARY KEY,
    answerId UUID REFERENCES ANSWERS(answerId) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    optionId UUID REFERENCES OPTIONS(optionId) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);