CREATE TABLE ANSWERS (
    answerId UUID PRIMARY KEY,
    submissionId UUID NOT NULL REFERENCES SUBMISSIONS(submissionId) ON DELETE CASCADE ON UPDATE CASCADE,
    questionId UUID NOT NULL REFERENCES QUESTIONS(questionId) ON DELETE CASCADE ON UPDATE CASCADE,
    answeredAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);