CREATE TABLE IF NOT EXISTS ATTENDANCES (
    attendanceId UUID PRIMARY KEY,
    attendanceTimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    signedWith signed_with_type NOT NULL,
    signedBy    UUID NOT NULL REFERENCES USERS(userId) ON DELETE CASCADE ON UPDATE CASCADE,
    userId      UUID NOT NULL REFERENCES USERS(userId) ON DELETE CASCADE ON UPDATE CASCADE,
    areaId      UUID NOT NULL REFERENCES AREAS(areaId) ON DELETE CASCADE ON UPDATE CASCADE
);