CREATE TABLE PROJECT_USER_ROLES (
    projectUserRoleId UUID PRIMARY KEY,
    userId UUID NOT NULL REFERENCES USERS(userId) ON DELETE CASCADE ON UPDATE CASCADE,
    projectId UUID NOT NULL REFERENCES PROJECTS(projectId) ON DELETE CASCADE ON UPDATE CASCADE,
    roleId UUID NOT NULL REFERENCES ROLES(roleId) ON DELETE CASCADE ON UPDATE CASCADE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_project UNIQUE (userId, projectId)
);