CREATE TABLE QUESTIONS (
    questionId UUID PRIMARY KEY,
    typeCode VARCHAR(30) NOT NULL REFERENCES QUESTION_TYPES(typeCode) ON DELETE CASCADE ON UPDATE CASCADE,
    questionText JSONB NOT NULL,
    formId UUID NOT NULL REFERENCES FORMS(formId) ON DELETE CASCADE ON UPDATE CASCADE,
    interviewId UUID NOT NULL REFERENCES INTERVIEWS(interviewId) ON DELETE CASCADE ON UPDATE CASCADE
);