CREATE TABLE ROLE_ACTIONS (
    roleActionsId UUID PRIMARY KEY,
    roleId UUID NOT NULL REFERENCES ROLES(roleId) ON DELETE CASCADE ON UPDATE CASCADE,
    actionId UUID NOT NULL REFERENCES ACTIONS(actionId) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (roleId, actionId)
);