CREATE TABLE RULE_CRITERIA (
    ruleId UUID NOT NULL REFERENCES DECISION_RULES(ruleId) ON DELETE CASCADE ON UPDATE CASCADE,
    criterionId UUID NOT NULL REFERENCES CRITERIA(criterionId) ON DELETE CASCADE ON UPDATE CASCADE,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ruleId, criterionId)
);