CREATE TABLE SCHEDULES (
    scheduleId UUID PRIMARY KEY,
    createdAt DATE NOT NULL DEFAULT CURRENT_DATE,
    startTime TIME NOT NULL ,
    endTime TIME NOT NULL ,
    projectId UUID  REFERENCES PROJECTS(projectId) ON DELETE CASCADE ON UPDATE CASCADE,
    locationId UUID  REFERENCES LOCATIONS(locationId) ON DELETE CASCADE ON UPDATE CASCADE
  CHECK (
       (projectId  IS NOT NULL AND locationId IS     NULL)
    OR (projectId  IS     NULL AND locationId IS NOT NULL)
    )
    
);