CREATE TABLE SCHEDULES (
    scheduleId UUID PRIMARY KEY,
    createdAt DATE NOT NULL DEFAULT CURRENT_DATE,
    startTime TIME NOT NULL ,
    endTime TIME NOT NULL ,
    projectId UUID NOT NULL REFERENCES PROJECTS(projectId) ON DELETE CASCADE ON UPDATE CASCADE,
    locationId UUID NOT NULL REFERENCES LOCATIONS(locationId) ON DELETE CASCADE ON UPDATE CASCADE

    CONSTRAINT unique_project_location UNIQUE (projectId, locationId)

    
);