CREATE TABLE USER_PROJECT (
    userProjectId UUID PRIMARY KEY,
    userId UUID NOT NULL REFERENCES USERS(userId) ON DELETE CASCADE ON UPDATE CASCADE,
    projectId UUID NOT NULL REFERENCES PROJECTS(projectId) ON DELETE CASCADE ON UPDATE CASCADE
);