CREATE TABLE ANSWERS (
    answerId UUID PRIMARY KEY,
    submissionId UUID NOT NULL REFERENCES SUBMISSION(submissionId),
    questionId UUID NOT NULL REFERENCES QUESTIONS(questionId),
    answeredAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);