CREATE TABLE ATTENDANCES (
    attendanceId UUID PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TIME NOT NULL DEFAULT CURRENT_TIME,
    signedWith signed_with_type NOT NULL,
    signedBy UUID NOT NULL REFERENCES USERS(userId),
    userId UUID NOT NULL REFERENCES USERS(userId),
    areaId UUID NOT NULL REFERENCES AREAS(areaId)
);