CREATE TABLE PROJECT_USER_ROLES (
    projectUserRoleId UUID PRIMARY KEY,
    userId UUID NOT NULL REFERENCES USERS(userId),
    projectId UUID NOT NULL REFERENCES PROJECTS(projectId),
    roleId UUID NOT NULL REFERENCES ROLES(roleId)
);