CREATE TABLE PROJECT_USER_AUTHORITIES (
    projectUserAuthoritiesId UUID PRIMARY KEY,
    userId UUID NOT NULL REFERENCES USERS(userId),
    projectId UUID NOT NULL REFERENCES PROJECTS(projectId),
    authorityId UUID NOT NULL REFERENCES AUTHORITIES(authorityId)
);