CREATE TABLE QUESTIONS (
    questionId UUID PRIMARY KEY,
    typeCode VARCHAR(30) NOT NULL REFERENCES QUESTION_TYPES(typeCode),
    questionText VARCHAR(1000) NOT NULL,
    formId UUID NOT NULL REFERENCES FORMS(formId),
    interviewId UUID NOT NULL REFERENCES INTERVIEW(interviewId)
);