CREATE TABLE RULE_CRITERIA (
    ruleId UUID NOT NULL REFERENCES DECISION_RULES(ruleId),
    criterionId UUID NOT NULL REFERENCES CRITERIA(criterionId),
    required BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ruleId, criterionId)
);