CREATE TABLE SCHEDULE (
    scheduleId UUID PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    startTime TIME NOT NULL DEFAULT '08:00',
    endTime TIME NOT NULL DEFAULT '14:00',
    projectId UUID NOT NULL REFERENCES PROJECTS(projectId),
    locationId UUID NOT NULL REFERENCES LOCATIONS(locationId)
);